name: Deno Test
# When there is a push to master, this script will run it with Deno to make sure it works
on:
  push:
    branches: [ master ]

jobs:
  run_deno:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2.3.0
      - run: deno run --allow-net index.ts
